---
- hosts: all
  become: yes
  tasks:
    - name: Install AWS SSM Agent on Linux
      ansible.builtin.shell: |
        if [ -f /etc/debian_version ]; then
          curl "https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/debian_amd64/amazon-ssm-agent.deb" -o "amazon-ssm-agent.deb"
          dpkg -i amazon-ssm-agent.deb
        elif [ -f /etc/redhat-release ]; then
          yum install -y https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm
        fi
      when: ansible_os_family != "Windows"
    
    - name: Install AWS SSM Agent on Windows
      win_shell: |
        Invoke-WebRequest -Uri https://s3.amazonaws.com/amazon-ssm-us-east-1/latest/windows_amd64/AmazonSSMAgentSetup.exe -OutFile $env:TEMP\AmazonSSMAgentSetup.exe
        Start-Process -FilePath $env:TEMP\AmazonSSMAgentSetup.exe -ArgumentList /S -Wait
      when: ansible_os_family == "Windows"
